### ISSUE TITLE
No module names 'chardet'

### ISSUE THREAD

**Issue by nicost** [stardist/stardist-napari#22] opened 2023-03-15 20:34 UTC
**Describe the bug**
In a conda environment (pyython=3.10), install tensorflow, starDist, napari, and starDist-napari:
```
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
python -m pip install "tensorflow<2.11"
pip install stardist
conda install jupyter
python -m pip install "napari[all]"
pip install stardist-napari
```

running "napari" yields:
```
Traceback (most recent call last):
  File "C:\Users\nstuurman\.conda\envs\starDist\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

```
**To reproduce**
See above

**Expected behavior**
Napari starting with starDist as a plugin

**Data and screenshots**
If applicable, add data (e.g. images) or screenshots to help explain your problem.

**Environment:**

1. Please copy and paste the information at napari info option in the help menubar.

2. Please run this code and paste the output:
```python
import importlib, platform

print(f'os: {platform.platform()}')
for m in ('stardist_napari','stardist','csbdeep','napari','magicgui','tensorflow'):
    try:
        print(f'{m}: {importlib.import_module(m).__version__}')
    except ModuleNotFoundError:
        print(f'{m}: not installed')
```

os: Windows-10-10.0.19044-SP0

for m in ('stardist_napari','stardist','csbdeep','napari','magicgui','tensorflow'):
    try:
        print(f'{m}: {importlib.import_module(m).__version__}')
    except ModuleNotFoundError:
        print(f'{m}: not installed')

Note: Fixed by 
`conda install chardet`
but I guess that means it should be decalred as a dependency somewhere.

**Comment by maweigert** [comment] 2023-03-17 09:54
Hi @nicost , thanks for raising an issue!

I don't think this is related to stardist and I cannot reproduce this on linux with a similar setup such as yours:

```
os: Linux-5.4.0-139-generic-x86_64-with-glibc2.31
stardist_napari: 2022.12.6
stardist: 0.8.3
csbdeep: 0.7.3
napari: 0.4.17
magicgui: 0.7.2
tensorflow: 2.10.1
```
Can you send us the corresponding version of your (failing) environment? (it got messed up in your original issue)

**Comment by nicost** [comment] 2023-03-20 22:06
Environment:

os: Windows-10-10.0.19044-SP0
stardist_napari: 2022.12.6
stardist: 0.8.3
csbdeep: 0.7.3
napari: 0.4.17
magicgui: 0.7.2
tensorflow: 2.10.1

Looks quite identical to yours (except for the OS).  This is not a big deal (as it is so easily fixed), just trying to help streamline things for those who come behind me;).  Feel free to close.

**Comment by maweigert** [comment] 2023-03-21 23:54
Ok, thx! I think this is related to a specific environment and (as you indicated) should be easy to fix (thus closing).

**Closed by maweigert** 2023-03-21 23:54 UTC
Labels: bug
